### ISSUE TITLE
Official project migration?

### ISSUE THREAD

**Issue by pfalcon** [joxeankoret/pyew#30]
Please kindly change default migration description, preferrably mentioning that this is the official migration by the author (search github for "pyew" to see why). Also, please capture original https://code.google.com/p/pyew/ page as README, etc, etc.

Thanks.

**Comment by joxeankoret** [comment]
Yes, yes. It's still in the process of official migration because the "Export to GitHub" option in GoogleCode is (or was) broken. I need to re-import it correctly (i.e., by hand).

**Comment by pfalcon** [comment]
Thanks for the response! I heard (at least 3 days ago) that python's tulip/asyncio project had problems with migration (missing issue tickets IIRC), and google made some fixes for them, so you may want to give another automatic try. But yes, it's strange it didn't migrate wiki (in gcode, it's also backed by a VCS, right?)

**Comment by pfalcon** [comment]
Well, wiki lives in a separate branch. You can "cherry-pick" a main page out of it (worked well for https://github.com/pfalcon/pymsasid ), the rest can be pushed to a separate wiki repo as used by github.

**Comment by joxeankoret** [comment]
Yes, I have seen it. As soon as I have time (this weekend?) I will finish the migration.

**Comment by joxeankoret** [comment]
Sorry for taking ~1 year :/
