### ISSUE TITLE
release

### ISSUE THREAD

**Issue by shibumi** [joxeankoret/pyew#31]
Hello,
Could you please use the release function in github? this would make it more easier to package your software :) thx!

cheers

chris

**Comment by joxeankoret** [comment]
Yes, yes. The idea is to finish the 1.1 milestone and then always use the release system. But once there is a true release. I should have done it before but, well, I didn't.

**Comment by joxeankoret** [comment]
Oh, sorry, I thought it was for another project :) I will do it as some as I have time to package the 3 ones: Windows, Linux and OSX.

**Comment by shibumi** [comment]
thx! Would be awesome. I want to make a AUR (Archlinux User Repository) Package out of pyew.

**Comment by joxeankoret** [comment]
Cool! I will do this weekend.

**Comment by shibumi** [comment]
cool! I will wait for it and inform you then I have packaged it.

**Comment by shibumi** [comment]
*bump*

**Comment by joxeankoret** [comment]
So sorry, I will do this week.

**Comment by joxeankoret** [comment]
I will use that feature in the future. For now, it makes no sense (I guess.)
