### ISSUE TITLE
syntax error while compiling

### ISSUE THREAD

**Issue by shibumi** [joxeankoret/pyew#33]
File "./vstruct/defs/windows/win_5_1_i386/win32k.py", line 358
    class ACCESS_STATE::__unnamed(vstruct.VStruct):
                       ^
SyntaxError: invalid syntax

**Comment by joxeankoret** [comment]
Version of python, please?

**Comment by shibumi** [comment]
Python 2.7.12

**Comment by joxeankoret** [comment]
Sounds weird, should work properly. Is it Linux?

**Comment by shibumi** [comment]
I am not running it, I want to compile it for faster execution:
Try this in the pyew root dir. This is the standard procedure what we do in Arch Linux with bigger python projects for better benchmarks.
```
  python2 -m compileall .
  python2 -O -m compileall .
```

**Comment by joxeankoret** [comment]
Oh, that's different! From what I can tell, it seems that file is never used by VTrace (the part that is failing.) So, it was as easy as removing that file (and a little mod in the z80 disassembler also from VTrace).

Fixed with 41d3d78b9cee79fa398c15a0b45200209ba1cb3b
